name: Deploy NexHire Backend to Azure Functions

on:
  push:
    branches: [ main, frontend, develop ]
    paths: 
      - 'src/**'
      - 'index.ts'
      - 'package.json'
      - 'host.json'
      - 'tsconfig.json'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: nexhire-api-func
  NODE_VERSION: '20.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: 'Setup Node.js'
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: 'Install dependencies'
      run: npm ci

    - name: 'Build TypeScript'
      run: npm run build

    - name: 'Deploy to Azure Functions'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '.'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

    - name: 'Wait for deployment'
      run: sleep 60

    - name: 'Test APIs'
      run: |
        echo "Testing health endpoint..."
        curl -f https://nexhire-api-func.azurewebsites.net/api/health || echo "Health check pending..."
        
        echo "Testing countries API..."
        curl -f https://nexhire-api-func.azurewebsites.net/api/reference/countries | head -200 || echo "Countries API pending..."

    - name: 'Deployment Complete'
      run: |
        echo "?? Deployment finished!"
        echo "Health: https://nexhire-api-func.azurewebsites.net/api/health"
        echo "Countries: https://nexhire-api-func.azurewebsites.net/api/reference/countries"