name: Deploy NexHire Backend to Azure Functions

on:
  push:
    branches: [ main, frontend, develop ]
    paths:
      - 'src/**'
      - 'index.ts'
      - 'package.json'
      - 'host.json'
      - 'tsconfig.json'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: nexhire-api-func
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '20.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: 'Setup Node.js'
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: 'Install dependencies'
      run: npm ci

    - name: 'Build TypeScript'
      run: npm run build

    - name: 'Verify build output'
      run: |
        echo "Checking build output..."
        ls -la dist/
        echo "Checking main entry point..."
        head -20 dist/index.js
        echo "Verifying countries controller..."
        grep -n "getCountries" dist/src/controllers/reference.controller.js || echo "getCountries not found"

    - name: 'Deploy to Azure Functions'
      uses: Azure/functions-action@v1
      id: deploy
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

    - name: 'Verify deployment succeeded'
      run: |
        if [ "${{ steps.deploy.outcome }}" != "success" ]; then
          echo "? Deployment failed!"
          exit 1
        else
          echo "? Deployment reported success"
        fi

    - name: 'Wait for Azure Functions to warm up'
      run: |
        echo "Waiting for Azure Functions to initialize..."
        sleep 120

    - name: 'Test deployment with strict validation'
      run: |
        echo "Testing deployed functions with strict validation..."
        
        # Test health endpoint
        echo "Testing health endpoint..."
        HEALTH_RESPONSE=$(curl -s -w "%{http_code}" https://nexhire-api-func.azurewebsites.net/api/health)
        HEALTH_CODE="${HEALTH_RESPONSE: -3}"
        
        if [ "$HEALTH_CODE" = "200" ]; then
          echo "? Health endpoint working (200)"
        else
          echo "? Health endpoint failed ($HEALTH_CODE)"
          echo "Full response: $HEALTH_RESPONSE"
          
          # Try one more time after additional wait
          echo "Waiting additional 60 seconds and retrying..."
          sleep 60
          RETRY_RESPONSE=$(curl -s -w "%{http_code}" https://nexhire-api-func.azurewebsites.net/api/health)
          RETRY_CODE="${RETRY_RESPONSE: -3}"
          
          if [ "$RETRY_CODE" = "200" ]; then
            echo "? Health endpoint working after retry (200)"
          else
            echo "? Health endpoint still failing after retry ($RETRY_CODE)"
            echo "? DEPLOYMENT VERIFICATION FAILED"
            exit 1
          fi
        fi
        
        # Test countries API
        echo "Testing countries API..."
        COUNTRIES_RESPONSE=$(curl -s -w "%{http_code}" https://nexhire-api-func.azurewebsites.net/api/reference/countries)
        COUNTRIES_CODE="${COUNTRIES_RESPONSE: -3}"
        
        if [ "$COUNTRIES_CODE" = "200" ]; then
          echo "? Countries API working (200)"
          echo "Sample response:"
          echo "$COUNTRIES_RESPONSE" | head -500
        else
          echo "? Countries API failed ($COUNTRIES_CODE)"
          echo "? COUNTRIES API VERIFICATION FAILED"
          exit 1
        fi

    - name: 'Deployment Success Summary'
      run: |
        echo "?? DEPLOYMENT SUCCESSFUL!"
        echo "=================================="
        echo "? Build: Completed"
        echo "? Deploy: Success"
        echo "? Health Check: Working"
        echo "? Countries API: Working with flag emojis"
        echo ""
        echo "?? API Endpoints:"
        echo "• Health: https://nexhire-api-func.azurewebsites.net/api/health"
        echo "• Countries: https://nexhire-api-func.azurewebsites.net/api/reference/countries"
        echo "• Colleges: https://nexhire-api-func.azurewebsites.net/api/reference/colleges"
        echo ""
        echo "?? Your countries API with proper flag emojis is now live!"